---
title: "PCA and NMDS analysis"
output: PCA_notebook
---

 
Download and install packages 
```{r}
install.packages(c("splitstackshape", "reshape2", "ecodist", "devtools", "ggbiplot", "vegan", "plyr"))
install_github("vqv/ggbiplot")

x = c("splitstackshape", "reshape2", "ecodist", "devtools", "ggbiplot", "vegan", "ggplot2", "dplyr", "plyr")
lapply(x, require, character.only = TRUE)
```

Clean the data for NMDS and PCA analysis 

```{r}
raw_abundance <- read.csv("~/RCode/culture_abundance.csv", header=TRUE)
data <- raw_abundance
data <- cSplit(data, 'ID', '|')
data <- plyr::rename(data, c("ID_1"="Kingdom", "ID_2"="Phylum", "ID_3"="Class", "ID_4"="Order","ID_5"="Family",
                             "ID_6"="Genius", "ID_7"="Species", "ID_8"="Strain"))
data <- data %>% select(Kingdom:Strain, everything())
class_data <- data %>% filter(Class != "NA") 
class_data <- class_data[is.na(class_data$Order),]
class_data <- select(class_data, Class, X1062_RE_50:X1295_BF_100)
class_data <- as.data.frame(t(class_data), stringsAsFactors = FALSE)
colnames(class_data) <- class_data[1,]  # the first row will be the header
class_data <- class_data[-1, ]
class_data$Sample_ID <- rownames(class_data)
class_data[,1:9] <- apply(class_data[,1:9], 2, FUN = as.numeric)
class_data$Rain <- ifelse(grepl("RE", class_data$Sample_ID, ignore.case = T), "Rain Event", 
                          ifelse(grepl("BF", class_data$Sample_ID, ignore.case = T), "Baseflow", "Others")) 
colnames(class_data) <- gsub("c__", "", colnames(class_data))
```

NDMS analysis and plot the NMDS plot 
```{r}
#nmds
class.mds <- metaMDS(class_data[,1:9]) 
data.scores <- as.data.frame(scores(class.mds))  #Using the scores function from vegan to extract the site scores and convert to a data.frame
data.scores$Rain <- class_data$Rain

#nmds_ggplot
ggplot(data.scores, aes(x=NMDS1,y=NMDS2, color = factor(Rain),label=rownames(data.scores))) + 
  geom_text(aes(colour = factor(Rain)), size=6) +
  scale_colour_discrete(name = "Rain Condition",l = 40) +
  ylim(-0.70,0.70) +
  xlim(-1.0,1.0) +
  theme(axis.text=element_text(size=11, color ="black"),
        axis.title.y=element_text(size=14,face="bold", vjust=1), 
        axis.title.x=element_text(size=14,face="bold", vjust=-0.1)) +
  theme_bw(base_size = 15) 
```

PCA analysis and PCA plot 

```{r}
#pca
class.pca <- prcomp(class_data[,1:9],
                    center = TRUE,
                    scale. = TRUE) 


ggbiplot(class.pca, obs.scale = 1, var.scale = 1, groups = class_data$Rain, ellipse = FALSE, 
         circle = TRUE, varname.size = 3) + 
  scale_color_discrete(name = "") + 
  theme(legend.direction = 'horizontal', legend.position = 'top') +
  geom_text(aes(label=rownames(class_data), colour = factor(class_data$Rain)),size=4) +
  ylim(-5,4) +
  xlim(-5,7) +
  theme(axis.text=element_text(size=11, color ="black"),
        axis.title.y=element_text(size=14,face="bold", vjust=1), 
        axis.title.x=element_text(size=14,face="bold", vjust=-0.1)) +
  theme_bw(base_size = 15) 
```

Modify PCA plot to separate Baseflow and Rain Event on the plot 

```{r}
ggbiplot(class.pca, obs.scale = 1, var.scale = 1, groups = class_data$Rain, ellipse = TRUE, 
         circle = FALSE, varname.size = 4, varname.col = "black", labels.size = 10, labels.col="black") + 
  geom_point(aes(color=factor(class_data$Rain)), size=3) +
  scale_color_manual(values=c("blue", "red", "dark green"), name="") +
  theme(legend.direction = 'horizontal', legend.position = 'top') +
  ylim(-6,5) +
  xlim(-8,7) +
  theme(axis.text=element_text(size=10, color ="black"),
        axis.title.y=element_text(size=10,face="bold", vjust=1), 
        axis.title.x=element_text(size=10,face="bold", vjust=-0.1)) +
  theme_bw(base_size = 14)
```

